"""empty message

Revision ID: 0f07cd3877c3
Revises: 
Create Date: 2021-02-27 10:22:14.687942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f07cd3877c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('category_ibfk_1', 'category', type_='foreignkey')
    op.create_foreign_key(None, 'category', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('todo_list_ibfk_1', 'todo_list', type_='foreignkey')
    op.create_foreign_key(None, 'todo_list', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo_list', type_='foreignkey')
    op.create_foreign_key('todo_list_ibfk_1', 'todo_list', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.create_foreign_key('category_ibfk_1', 'category', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
